<?php

namespace KhgProxy\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class KhgManufacturer extends \KhgManufacturer implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setName($pName)
    {
        $this->__load();
        return parent::setName($pName);
    }

    public function setDescription($pDescription)
    {
        $this->__load();
        return parent::setDescription($pDescription);
    }

    public function setAddress($pAddress)
    {
        $this->__load();
        return parent::setAddress($pAddress);
    }

    public function setPhoneNumber($pNumber)
    {
        $this->__load();
        return parent::setPhoneNumber($pNumber);
    }

    public function setEmail($pEmail)
    {
        $this->__load();
        return parent::setEmail($pEmail);
    }

    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function getPhoneNumber()
    {
        $this->__load();
        return parent::getPhoneNumber();
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function getItems()
    {
        $this->__load();
        return parent::getItems();
    }

    public function copyFrom($pManufacturer)
    {
        $this->__load();
        return parent::copyFrom($pManufacturer);
    }


    public function __sleep()
    {
        return array('__isInitialized__', '_name', '_description', '_address', '_phoneNumber', '_email', '_manufacturerId', '_items');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}